apiVersion: v1
kind: Service
metadata:
  name: {{ include "scouterapm.fullname" . }}
  labels:
    {{- include "scouterapm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: web
      protocol: TCP
      name: web2
      nodePort: {{ .Values.web.node.port }}
    - port: {{ .Values.service.port }} 
      targetPort: http
      protocol: TCP
      name: http2
      nodePort: {{ .Values.service.node.port }}
    - port: {{ .Values.udp.port  }}
      targetPort: udp
      name: udp2
      protocol: UDP
      nodePort: {{ .Values.udp.node.port }}   
  selector:
    {{- include "scouterapm.selectorLabels" . | nindent 4 }}
